/**
 * API C wrapper for the SMART Response SDK.
 * Copyright (C) 2010 SMART Technologies ULC. All rights reserved.
 */

#ifndef SMARTRESPONSEAPIVERSIONING_H
#define SMARTRESPONSEAPIVERSIONING_H

// base api
#define sr_sdk_stringlength smartresponse_sdk_stringlength 
#define sr_sdk_initialize smartresponse_sdk_initialize 
#define sr_sdk_terminate smartresponse_sdk_terminate 
#define sr_listener_release smartresponse_listener_release 
#define sr_condition_create smartresponse_condition_create 
#define sr_condition_wait smartresponse_condition_wait 
#define sr_condition_notify smartresponse_condition_notify 
#define sr_condition_release smartresponse_condition_release 

// class api 
#define sr_classroom_name smartresponse_classroom_name 
#define sr_class_title smartresponse_class_title 
#define sr_set_classroom_name smartresponse_set_classroom_name
#define sr_create_class sr_class_create
#define sr_release_class sr_class_release
#define sr_add_student_to_class sr_class_addstudent

// connection api
#define sr_connection_create smartresponse_connectionV1_create 
#define sr_connection_release smartresponse_connectionV1_release 
#define sr_connection_copyerrorinfo smartresponse_connectionV1_copyerrorinfo 
#define sr_connection_listenonconnected smartresponse_connectionV1_listenonconnected
#define sr_connection_listenonconnectiondidfail smartresponse_connectionV1_listenonconnectiondidfail 
#define sr_connection_connect smartresponse_connectionV1_connect
#define sr_connection_listenondisconnected smartresponse_connectionV1_listenondisconnected
#define sr_connection_disconnect smartresponse_connectionV1_disconnect
#define sr_connection_listenonclassstarted smartresponse_connectionV1_listenonclassstarted 
#define sr_connection_listenonclassfailtostart smartresponse_connectionV1_listenonclassfailtostart
#define sr_connection_startclass smartresponse_connectionV2_startclass 
#define sr_connection_currentclass smartresponse_connectionV1_currentclass 
#define sr_connection_listenonclassstopped smartresponse_connectionV1_listenonclassstopped 
#define sr_connection_listenonclassfailtostop smartresponse_connectionV1_listenonclassfailtostop 
#define sr_connection_stopclass smartresponse_connectionV1_stopclass 
#define sr_connection_listenonquestionstarted smartresponse_connectionV1_listenonquestionstarted 
#define sr_connection_listenonquestionfailtostart smartresponse_connectionV1_listenonquestionfailtostart 
#define sr_connection_startquestion smartresponse_connectionV1_startquestion 
#define sr_connection_currentquestion smartresponse_connectionV1_currentquestion 
#define sr_connection_listenonquestionstopped smartresponse_connectionV1_listenonquestionstopped 
#define sr_connection_listenonquestionfailtostop smartresponse_connectionV1_listenonquestionfailtostop 
#define sr_connection_stopquestion smartresponse_connectionV1_stopquestion 
#define sr_connection_endreviewmode smartresponse_connectionV1_endreviewmode 
#define sr_connection_listenonreceiverpluggedin smartresponse_connectionV1_listenonreceiverpluggedin 
#define sr_connection_listenonreceiverready smartresponse_connectionV1_listenonreceiverready 
#define sr_connection_listenonreceiverunplugged smartresponse_connectionV1_listenonreceiverunplugged 
#define sr_connection_listenonclickerconnected smartresponse_connectionV1_listenonclickerconnected 
#define sr_connection_listenonclickerdisconnected smartresponse_connectionV1_listenonclickerdisconnected 
#define sr_connection_listenonclickerquestioned smartresponse_connectionV1_listenonclickerquestioned 
#define sr_connection_listenonclickerquestioncanceled smartresponse_connectionV1_listenonclickerquestioncanceled 
#define sr_connection_listenonclickerresponded smartresponse_connectionV1_listenonclickerresponded 
#define sr_connection_listenonclickersubmitted smartresponse_connectionV1_listenonclickersubmitted
#define sr_connection_listenonquestionsetstarted smartresponse_connectionV1_listenonquestionsetstarted 
#define sr_connection_listenonquestionsetfailtostart smartresponse_connectionV1_listenonquestionsetfailtostart 
#define sr_connection_startquestionset smartresponse_connectionV1_startquestionset 
#define sr_connection_listenonquestionsetstopped smartresponse_connectionV1_listenonquestionsetstopped 
#define sr_connection_listenonquestionsetfailtostop smartresponse_connectionV1_listenonquestionsetfailtostop 
#define sr_connection_stopquestionset smartresponse_connectionV1_stopquestionset 
#define sr_connection_currentquestionset smartresponse_connectionV1_currentquestionset 
#define sr_connection_isreceiverready smartresponse_connectionV1_isreceiverready 

#define sr_connection_construct() sr_connection_create(SMARTRESPONSE_INVOKE_CALLBACKS_ON_MAIN_THREAD_ONLY)

// error info api
#define sr_errorinfo_release smartresponse_errorinfoV1_release 
#define sr_errorinfo_statuscode smartresponse_errorinfoV1_statuscode 
#define sr_errorinfo_statustext smartresponse_errorinfoV1_statustext 
#define sr_errorinfo_fulldetails smartresponse_errorinfoV1_fulldetails 
#define sr_errorinfo_unsupportedquestions smartresponse_errorinfoV1_unsupportedquestions 

// features api

#define sr_features_supported smartresponse_featuresV1_supported 
#define sr_features_questionchoicenumber smartresponse_featuresV1_questionchoicenumber 
#define sr_features_questionselectionnumber smartresponse_featuresV1_questionselectionnumber 
#define sr_features_numericanswerlength smartresponse_featuresV1_numericanswerlength 
#define sr_features_textanswerlength smartresponse_featuresV1_textanswerlength 
#define sr_features_textanswervalid smartresponse_featuresV1_textanswervalid 
#define sr_features_maxquestionsperquestionset smartresponse_featuresV1_maxquestionsperquestionset


// question api
#define sr_question_create smartresponse_questionV1_create 
#define sr_question_release smartresponse_questionV1_release 
#define sr_question_type smartresponse_questionV1_type 
#define sr_question_questiontext smartresponse_questionV1_questiontext 
#define sr_question_setquestiontext smartresponse_questionV1_setquestiontext 
#define sr_question_answer smartresponse_questionV1_answer 
#define sr_question_setanswer smartresponse_questionV1_setanswer 
#define sr_question_choicecount smartresponse_questionV1_choicecount 
#define sr_question_choicetext smartresponse_questionV1_choicetext 
#define sr_question_setchoicetext smartresponse_questionV1_setchoicetext 
#define sr_question_questionpoints smartresponse_questionV1_questionpoints 
#define sr_question_setquestionpoints smartresponse_questionV1_setquestionpoints 

// question set api
#define sr_questionset_create smartresponse_questionsetV1_create 
#define sr_questionset_release smartresponse_questionsetV1_release 
#define sr_questionset_points smartresponse_questionsetV1_points 
#define sr_questionset_name smartresponse_questionsetV1_name 
#define sr_questionset_setname smartresponse_questionsetV1_setname 
#define sr_questionset_questioncount smartresponse_questionsetV1_questioncount 
#define sr_questionset_setquestion smartresponse_questionsetV1_setquestion 
#define sr_questionset_question smartresponse_questionsetV1_question 

#endif
